DROP DATABASE IF EXISTS dog_dateDB;
CREATE DATABASE dog_dateDB;

USE dog_datedb;

CREATE TABLE owners (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(26) NOT NULL,
email VARCHAR(50) NOT NULL,
PRIMARY KEY (id)
)

SELECT * FROM owners;

CREATE TABLE dogs (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(26) NOT NULL,
breed VARCHAR(26) NOT NULL,
size INT(1) NOT NULL,
picture TEXT NOT NULL,
personality INT(1) NOT NULL,
age INT(1) NOT NULL,
PRIMARY KEY (id)
)

SELECT * FROM dogs;